# Change these first
owner: egoriseehear # Your GitHub organization or username, where this repository lives
repo: test-upptime # The name of this repository

sites:
  - name: iseethere.com
    url: http://www.iseethere.com

status-website:

  links:
    - rel: stylesheet
      href: https://amenitylab.org/my_scss/main.css
      
  scripts:
  - src: https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js
    href: https://amenitylab.org/my_js/scrol.js
    async: true
    
  css: '
  .container { 
    font-size: 25px !important;
    max-width: 1000px !important;
    margin-top: 5rem;
    margin-bottom: 5rem; 
  }
  article.degraded {
    margin: 5rem 0 !important;
  }  
  ol, ul {
    list-style: none !important;
  }
  a {
    text-decoration: none !important;
  }
  .dropdown-menu {
    border: none !important;
    border-radius: 2rem !important;
    box-shadow: 0px 4px 18px rgb(88 126 236 / 25%) !important;
    left: auto !important;
    padding: 1rem !important;
  }
  .dropdown, .dropend, .dropstart, .dropup {
    position: static !important;
  }
  article.graph.svelte-fqsq6s.svelte-fqsq6s.svelte-fqsq6s {
    margin: 5rem 0 !important;
  }
  body {
  font-family: "Mulish", sans-serif !important;
  }
  '

  customBodyHtml: '
<!DOCTYPE html>
<html lang="en" style="font-size: 10px">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="scss/main.css">
    <title>softmouse-encryption</title>
</head>
<body>

<div class="wrapper">
<nav class="navbar navbar-expand-lg navbar-light myHeader">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><img class="logo" src="/amenitylab.org/img/iseehear-logo.png" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav dropDownBox">
                <li class="nav-item">
                    <a class="nav-link text text-hover fw-bold dashboard" href="https://amenitylab.org/">
                        Status Dashboard
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text text-hover fw-bold" href="/security-summary" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Data Security
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="text" href="/security-overview">Security Overview</a></li>
                        <li><a class="text" href="/softmouse-encryption">Softmouse Encryption</a></li>
                        <li><a class="text" href="/malware-detection">Malware Detection</a></li>
                        <li><a class="text" href="/password-management">Password Management</a></li>
                        <li><a class="text" href="/data-backup">Data Backup</a></li>
                        <li><a class="text" href="/disaster-recovery-research-continuity">Disaster Recovery</a></li>
                        <li><a class="text" href="/google-cloud-platform">Google Cloud Platform</a></li>
                        <li><a class="text" href="/whois-verification-authentication">WHOIS Verification & Authentication</a></li>
                        <li><a class="text" href="/browsers-support">Supported Internet Browsers</a></li>
                        <li><a class="text" href="/security-hygiene-tips">Security Hygiene Tips</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text text-hover fw-bold" href="/security-summary" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Policies
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="text" href="/policiesOverview">Iseehear Policies Overview</a></li>
                        <li><a class="text" href="/privacyPolicy">Iseehear Privacy Policy (Full Version)</a></li>
                        <li><a class="text" href="/termsOfUse">Iseehear Terms of Use</a></li>
                        <li><a class="text" href="/cookiePolicy">Iseehear Cookie Policy</a></li>
                        <li><a class="text" href="/emailPolicy">Iseehear Email Policy Notice</a></li>
                        <li><a class="text" href="/intellectualProperty">Iseehear Intellectual Property Research Data Rights Policy</a></li>
                        <li><a class="text" href="/freeTrialPolicy">Iseehear Free Trial Policy<a></li>
                        <li><a class="text" href="/copyright">Iseehear Copyright Policy</a></li>
                        <li><a class="text" href="/trademark">Iseehear Trademark Notice</a></li>
                        <li><a class="text" href="/betaSiteAgreement">Iseehear Beta Site Agreement</a></li>
                        <li><a class="text" href="/subscriptionAgreement">Iseehear Subscription Agreement</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text text-hover fw-bold" href="/communication-resources" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Communications
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="text" href="softmouse-upgrade-maintenance">Scheduled Upgrades And System Maintenance Procedures</a></li>
                        <li><a class="text" href="softmouse-emergency-maintenance">Emergency Upgrades And System Maintenance Procedures</a></li>
                        <li><a class="text" href="information-resources">Information Resource Links</a></li>
                        <li><a class="text" href="contact-us">Contact us Resources</a></li>
                        <li><a class="text" href="contactForm">Contact Us Web Form</a></li>
                        <li><a class="text" href="/newPage">new Page</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text text-hover fw-bold emergensy-planing" href="/emergency-plan" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Emergency
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="text" href="how-you-can-prepare">How you can prepare</a></li>
                        <li><a class="text" href="how-we-are-prepared">How we are prepared</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<script src="js/scrol.js"></script>
'
  
i18n:
    footer: '
        <footer class="footer">
                        <div class="container">
                            <div class="contactInfo">
                                <h2 class="subCaption">Support and Security</h2>
                            </div>
                            
                            <div class="contactInfo">
                                <h2 class="subCaption">Corporate Websites</h2>
                                <ul>
                                    <li>
                                        <a href="https://www.iseehear.info" target="_blank">
                                            <p class="text">Iseehear.INFO</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="http://www.iseehear.com" target="_blank" rel="nofollow">
                                            <p class="text">Iseehear.com</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.softmouse.net" target="_blank" rel="nofollow">
                                            <p class="text">SoftMouse.NET</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="http://www.softmousefaq.com" target="_blank" rel="nofollow">
                                            <p class="text">SoftMouseFAQ.com</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="http://www.breedingservices.com" target="_blank" rel="nofollow">
                                            <p class="text">BreedingServices.com</p>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            <div class="contactInfo">
                                <h2 class="subCaption">Contact Information</h2>        
                                <a href="https://iseehear.info/iseehear+contact.php" target="_blank">
                                    <button class="button">Contact Us</button>
                                </a> 
                                <p class="text">If you are experiencing an issue, please contact customer support.</p>
                                <p class="text">Phone: +1 416-492-4358</p>
                                <p class="text">Toll Free: 1 844 559 6322</p>
                            </div>
                        </div>
                        <a href="http://www.iseehear.com" target="_blank" rel="nofollow"> <img src="/amenitylab.org/img/iseehear-cloud-0005.png" class="img-responsive cloud-footer"></a>
                        <img src="/amenitylab.org/img/iseehear-health-check-0002.png" class="iseehearImg">
                        <div class="bottomLink">
                            <p class="text">2000 - 2019 Iseehear Inc. All rights reserved.</p>
                            <a target="_blank" href="http://www.iseehear.com/privacy.php" class="text" rel="nofollow">Privacy Policy</a> 
                            <p class="text">|</p> 
                            <a target="_blank" href="http://www.iseehear.com/terms+of+use.php" class="text" rel="nofollow">Terms of Use</a>
                        </div>
    </footer>
    '
 
        
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo
  introMessage: sample
#   navbar: name there
  cname: amenitylab.org
  baseUrl: /test-upptime
#   logoUrl: https://iseehear.com/img/iseehear-turning-data-into-scientific-insight-0003.png
#   name: Uptime
  introTitle: Up Time Check!
#     - title: Status
#       href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
